//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class lateness
    {
        public int id_lateness { get; set; }
        public System.TimeSpan login_time { get; set; }
        public int id_penalty { get; set; }
        public int id_employee { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual penalty penalty { get; set; }
    }
}
